name: GitHub Actions RJED
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/chekout@v2
      - name: Starting Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build project
        run: npm run start
